Added bulgarian translation.
horyu1234/SCPLIST-KR-Translations pull request #27
Opened 2023-01-28 20:31 UTC by gogo1701

2023-05-05 12:36 UTC, horyu1234 requested changes

2023-05-05 12:36 UTC, horyu1234 commented on locale/bg-BG.json
> +        "date-format": "гггг-мм-дд аа чч:мм",
`date-format` can only come in English. https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Pattern_Examples Refer to this link and modify it.

2023-05-05 12:40 UTC, gogo1701 commented on locale/bg-BG.json
> +        "date-format": "гггг-мм-дд аа чч:мм",
Didn't see that. Fixed it. Thanks!

2023-06-04 09:51 UTC, horyu1234 approved these changes

2023-06-04 09:51 UTC, merged